-- 자동 생성: generate-seeds.mjs — 직접 수정 금지, 원본 JSON 수정 후 재생성
-- 멱등: on conflict do update

insert into public.ontology_rules (tenant_id,rule_id,trigger_code,trigger_name,relation,targets,target_names,default_target,condition,quantity_calc,qty_formulas,priority,description,raw,origin_dataset)
values
('HQ','R001','P076','LGS 경량틀 (벽체)','REQUIRES',array['P078','P079']::text[],array['석고보드 단면 (9.5T)','석고보드 단면 (12.5T)']::text[],'P079',null,null,'{"P078":{"type":"multiply","factor":1},"P079":{"type":"multiply","factor":1}}'::jsonb,1,'LGS 경량틀 설치 시 석고보드 마감 필수','{"id":"R001","trigger":"P076","triggerName":"LGS 경량틀 (벽체)","requires":["P078","P079"],"requiresNames":["석고보드 단면 (9.5T)","석고보드 단면 (12.5T)"],"defaultTarget":"P079","relation":"REQUIRES","priority":1,"description":"LGS 경량틀 설치 시 석고보드 마감 필수","qtyFormulas":{"P078":{"type":"multiply","factor":1},"P079":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R002','P077','LGS 경량틀 (천장)','REQUIRES',array['P078','P079','P084']::text[],array['석고보드 단면 (9.5T)','석고보드 단면 (12.5T)','경량 천장 텍스 마감']::text[],'P078',null,null,'{"P078":{"type":"multiply","factor":1},"P079":{"type":"multiply","factor":1},"P084":{"type":"multiply","factor":1}}'::jsonb,1,'LGS 천장틀 설치 시 마감재 필수','{"id":"R002","trigger":"P077","triggerName":"LGS 경량틀 (천장)","requires":["P078","P079","P084"],"requiresNames":["석고보드 단면 (9.5T)","석고보드 단면 (12.5T)","경량 천장 텍스 마감"],"defaultTarget":"P078","relation":"REQUIRES","priority":1,"description":"LGS 천장틀 설치 시 마감재 필수","qtyFormulas":{"P078":{"type":"multiply","factor":1},"P079":{"type":"multiply","factor":1},"P084":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R003','P040','바닥 자기질 타일 (300)','REQUIRES',array['P047','P017']::text[],array['타일 줄눈 시공','우레탄 방수 (욕실)']::text[],'P047',null,null,'{"P047":{"type":"multiply","factor":1},"P017":{"type":"multiply","factor":1.1}}'::jsonb,1,'바닥타일 시공 시 줄눈 및 하부 방수 권장','{"id":"R003","trigger":"P040","triggerName":"바닥 자기질 타일 (300)","requires":["P047","P017"],"requiresNames":["타일 줄눈 시공","우레탄 방수 (욕실)"],"defaultTarget":"P047","relation":"REQUIRES","priority":1,"description":"바닥타일 시공 시 줄눈 및 하부 방수 권장","qtyFormulas":{"P047":{"type":"multiply","factor":1},"P017":{"type":"multiply","factor":1.1}}}'::jsonb,'ontology.json'),
('HQ','R004','P041','바닥 자기질 타일 (600)','REQUIRES',array['P047','P017']::text[],array['타일 줄눈 시공','우레탄 방수 (욕실)']::text[],'P047',null,null,'{"P047":{"type":"multiply","factor":1},"P017":{"type":"multiply","factor":1.1}}'::jsonb,1,'바닥타일 600 → 줄눈+방수','{"id":"R004","trigger":"P041","triggerName":"바닥 자기질 타일 (600)","requires":["P047","P017"],"requiresNames":["타일 줄눈 시공","우레탄 방수 (욕실)"],"defaultTarget":"P047","relation":"REQUIRES","priority":1,"description":"바닥타일 600 → 줄눈+방수","qtyFormulas":{"P047":{"type":"multiply","factor":1},"P017":{"type":"multiply","factor":1.1}}}'::jsonb,'ontology.json'),
('HQ','R005','P042','바닥 포세린 타일 (800)','REQUIRES',array['P047','P017','P036']::text[],array['타일 줄눈 시공','우레탄 방수 (욕실)','셀프레벨링 (바닥평탄화)']::text[],'P047',null,null,'{"P047":{"type":"multiply","factor":1},"P017":{"type":"multiply","factor":1.1},"P036":{"type":"multiply","factor":1}}'::jsonb,1,'대형 포세린 → 줄눈+방수+평탄화','{"id":"R005","trigger":"P042","triggerName":"바닥 포세린 타일 (800)","requires":["P047","P017","P036"],"requiresNames":["타일 줄눈 시공","우레탄 방수 (욕실)","셀프레벨링 (바닥평탄화)"],"defaultTarget":"P047","relation":"REQUIRES","priority":1,"description":"대형 포세린 → 줄눈+방수+평탄화","qtyFormulas":{"P047":{"type":"multiply","factor":1},"P017":{"type":"multiply","factor":1.1},"P036":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R006','P120','강마루 시공 (12T)','REQUIRES',array['P064','P063']::text[],array['목재 몰딩 설치','목재 걸레받이 설치']::text[],'P064',null,null,'{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"}}'::jsonb,1,'강마루 시공 시 몰딩+걸레받이 필수','{"id":"R006","trigger":"P120","triggerName":"강마루 시공 (12T)","requires":["P064","P063"],"requiresNames":["목재 몰딩 설치","목재 걸레받이 설치"],"defaultTarget":"P064","relation":"REQUIRES","priority":1,"description":"강마루 시공 시 몰딩+걸레받이 필수","qtyFormulas":{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"}}}'::jsonb,'ontology.json'),
('HQ','R007','P121','강마루 시공 (18T)','REQUIRES',array['P064','P063']::text[],array['목재 몰딩 설치','목재 걸레받이 설치']::text[],'P064',null,null,'{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"}}'::jsonb,1,'강마루 18T → 몰딩+걸레받이','{"id":"R007","trigger":"P121","triggerName":"강마루 시공 (18T)","requires":["P064","P063"],"requiresNames":["목재 몰딩 설치","목재 걸레받이 설치"],"defaultTarget":"P064","relation":"REQUIRES","priority":1,"description":"강마루 18T → 몰딩+걸레받이","qtyFormulas":{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"}}}'::jsonb,'ontology.json'),
('HQ','R008','P122','원목마루 시공','REQUIRES',array['P064','P063','P110']::text[],array['목재 몰딩 설치','목재 걸레받이 설치','목재 오일 스테인']::text[],'P064',null,null,'{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"},"P110":{"type":"multiply","factor":1}}'::jsonb,1,'원목마루 → 몰딩+걸레받이+오일스테인','{"id":"R008","trigger":"P122","triggerName":"원목마루 시공","requires":["P064","P063","P110"],"requiresNames":["목재 몰딩 설치","목재 걸레받이 설치","목재 오일 스테인"],"defaultTarget":"P064","relation":"REQUIRES","priority":1,"description":"원목마루 → 몰딩+걸레받이+오일스테인","qtyFormulas":{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"},"P110":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R009','P043','벽 세라믹 타일 (300)','REQUIRES',array['P047']::text[],array['타일 줄눈 시공']::text[],'P047',null,null,'{"P047":{"type":"multiply","factor":1}}'::jsonb,1,'벽 타일 → 줄눈 시공','{"id":"R009","trigger":"P043","triggerName":"벽 세라믹 타일 (300)","requires":["P047"],"requiresNames":["타일 줄눈 시공"],"defaultTarget":"P047","relation":"REQUIRES","priority":1,"description":"벽 타일 → 줄눈 시공","qtyFormulas":{"P047":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R010','P044','벽 대형 타일 (600)','REQUIRES',array['P048']::text[],array['타일 줄눈 시공 (광폭)']::text[],'P048',null,null,'{"P048":{"type":"multiply","factor":1}}'::jsonb,1,'대형 벽타일 → 광폭 줄눈','{"id":"R010","trigger":"P044","triggerName":"벽 대형 타일 (600)","requires":["P048"],"requiresNames":["타일 줄눈 시공 (광폭)"],"defaultTarget":"P048","relation":"REQUIRES","priority":1,"description":"대형 벽타일 → 광폭 줄눈","qtyFormulas":{"P048":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R011','P017','우레탄 방수 (욕실)','REQUIRES',array['P022']::text[],array['욕실 방수 보호몰탈']::text[],'P022',null,null,'{"P022":{"type":"multiply","factor":1}}'::jsonb,1,'욕실 방수 위 보호몰탈 필수','{"id":"R011","trigger":"P017","triggerName":"우레탄 방수 (욕실)","requires":["P022"],"requiresNames":["욕실 방수 보호몰탈"],"defaultTarget":"P022","relation":"REQUIRES","priority":1,"description":"욕실 방수 위 보호몰탈 필수","qtyFormulas":{"P022":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R012','P082','방수석고보드 (욕실용)','RECOMMENDS',array['P017','P043']::text[],array['우레탄 방수 (욕실)','벽 세라믹 타일 (300)']::text[],'P043',null,null,'{"P017":{"type":"multiply","factor":1},"P043":{"type":"multiply","factor":1}}'::jsonb,2,'욕실 방수석고보드 → 방수+타일 권장','{"id":"R012","trigger":"P082","triggerName":"방수석고보드 (욕실용)","requires":["P017","P043"],"requiresNames":["우레탄 방수 (욕실)","벽 세라믹 타일 (300)"],"defaultTarget":"P043","relation":"RECOMMENDS","priority":2,"description":"욕실 방수석고보드 → 방수+타일 권장","qtyFormulas":{"P017":{"type":"multiply","factor":1},"P043":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R013','P054','대리석 바닥 시공','RECOMMENDS',array['P059','P060']::text[],array['석재 연마/왁스','석재 코킹 처리']::text[],'P059',null,null,'{"P059":{"type":"multiply","factor":1},"P060":{"type":"perimeter"}}'::jsonb,2,'대리석 → 연마/왁스+코킹','{"id":"R013","trigger":"P054","triggerName":"대리석 바닥 시공","requires":["P059","P060"],"requiresNames":["석재 연마/왁스","석재 코킹 처리"],"defaultTarget":"P059","relation":"RECOMMENDS","priority":2,"description":"대리석 → 연마/왁스+코킹","qtyFormulas":{"P059":{"type":"multiply","factor":1},"P060":{"type":"perimeter"}}}'::jsonb,'ontology.json'),
('HQ','R014','P055','화강석 바닥 시공','RECOMMENDS',array['P059','P060']::text[],array['석재 연마/왁스','석재 코킹 처리']::text[],'P059',null,null,'{"P059":{"type":"multiply","factor":1},"P060":{"type":"perimeter"}}'::jsonb,2,'화강석 → 연마+코킹','{"id":"R014","trigger":"P055","triggerName":"화강석 바닥 시공","requires":["P059","P060"],"requiresNames":["석재 연마/왁스","석재 코킹 처리"],"defaultTarget":"P059","relation":"RECOMMENDS","priority":2,"description":"화강석 → 연마+코킹","qtyFormulas":{"P059":{"type":"multiply","factor":1},"P060":{"type":"perimeter"}}}'::jsonb,'ontology.json'),
('HQ','R015','P099','수성페인트 (내부 벽)','REQUIRES',array['P106','P105']::text[],array['퍼티 작업','페인트 하도 처리 (프라이머)']::text[],'P106',null,null,'{"P106":{"type":"multiply","factor":1},"P105":{"type":"multiply","factor":1}}'::jsonb,1,'벽 도장 전 퍼티+프라이머 필수','{"id":"R015","trigger":"P099","triggerName":"수성페인트 (내부 벽)","requires":["P106","P105"],"requiresNames":["퍼티 작업","페인트 하도 처리 (프라이머)"],"defaultTarget":"P106","relation":"REQUIRES","priority":1,"description":"벽 도장 전 퍼티+프라이머 필수","qtyFormulas":{"P106":{"type":"multiply","factor":1},"P105":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R016','P100','수성페인트 (천장)','REQUIRES',array['P105']::text[],array['페인트 하도 처리 (프라이머)']::text[],'P105',null,null,'{"P105":{"type":"multiply","factor":1}}'::jsonb,1,'천장 도장 전 프라이머 필수','{"id":"R016","trigger":"P100","triggerName":"수성페인트 (천장)","requires":["P105"],"requiresNames":["페인트 하도 처리 (프라이머)"],"defaultTarget":"P105","relation":"REQUIRES","priority":1,"description":"천장 도장 전 프라이머 필수","qtyFormulas":{"P105":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R017','P112','실크 도배','REQUIRES',array['P117']::text[],array['초배지 작업']::text[],'P117',null,null,'{"P117":{"type":"multiply","factor":1}}'::jsonb,1,'실크도배 → 초배 필수','{"id":"R017","trigger":"P112","triggerName":"실크 도배","requires":["P117"],"requiresNames":["초배지 작업"],"defaultTarget":"P117","relation":"REQUIRES","priority":1,"description":"실크도배 → 초배 필수","qtyFormulas":{"P117":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R018','P113','천연벽지 도배','REQUIRES',array['P117']::text[],array['초배지 작업']::text[],'P117',null,null,'{"P117":{"type":"multiply","factor":1}}'::jsonb,1,'천연벽지 → 초배 필수','{"id":"R018","trigger":"P113","triggerName":"천연벽지 도배","requires":["P117"],"requiresNames":["초배지 작업"],"defaultTarget":"P117","relation":"REQUIRES","priority":1,"description":"천연벽지 → 초배 필수","qtyFormulas":{"P117":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R019','P089','AL 창호 설치 (단열)','REQUIRES',array['P185','P184']::text[],array['EVA 폼 충전','코킹 방수 실리콘']::text[],'P185',null,null,'{"P185":{"type":"perimeter"},"P184":{"type":"perimeter"}}'::jsonb,1,'창호 설치 → 폼 충전+코킹 필수','{"id":"R019","trigger":"P089","triggerName":"AL 창호 설치 (단열)","requires":["P185","P184"],"requiresNames":["EVA 폼 충전","코킹 방수 실리콘"],"defaultTarget":"P185","relation":"REQUIRES","priority":1,"description":"창호 설치 → 폼 충전+코킹 필수","qtyFormulas":{"P185":{"type":"perimeter"},"P184":{"type":"perimeter"}}}'::jsonb,'ontology.json'),
('HQ','R020','P090','PVC 창호 설치','REQUIRES',array['P185','P184']::text[],array['EVA 폼 충전','코킹 방수 실리콘']::text[],'P185',null,null,'{"P185":{"type":"perimeter"},"P184":{"type":"perimeter"}}'::jsonb,1,'PVC창호 → 폼+코킹','{"id":"R020","trigger":"P090","triggerName":"PVC 창호 설치","requires":["P185","P184"],"requiresNames":["EVA 폼 충전","코킹 방수 실리콘"],"defaultTarget":"P185","relation":"REQUIRES","priority":1,"description":"PVC창호 → 폼+코킹","qtyFormulas":{"P185":{"type":"perimeter"},"P184":{"type":"perimeter"}}}'::jsonb,'ontology.json'),
('HQ','R021','P156','보일러 교체 (콘덴싱)','RECOMMENDS',array['P155','P164']::text[],array['난방 배관 설치 (온수)','가스 배관 (LNG)']::text[],'P155',null,null,'{"P155":{"type":"manual"},"P164":{"type":"manual"}}'::jsonb,2,'보일러 교체 → 배관+가스배관 점검 권장','{"id":"R021","trigger":"P156","triggerName":"보일러 교체 (콘덴싱)","requires":["P155","P164"],"requiresNames":["난방 배관 설치 (온수)","가스 배관 (LNG)"],"defaultTarget":"P155","relation":"RECOMMENDS","priority":2,"description":"보일러 교체 → 배관+가스배관 점검 권장","qtyFormulas":{"P155":{"type":"manual"},"P164":{"type":"manual"}}}'::jsonb,'ontology.json'),
('HQ','R022','P161','샤워부스 설치','REQUIRES',array['P017','P197']::text[],array['우레탄 방수 (욕실)','드레인 설치 (선형)']::text[],'P017',null,null,'{"P017":{"type":"fixed","value":4},"P197":{"type":"fixed","value":1.2}}'::jsonb,1,'샤워부스 → 방수+선형드레인 필수','{"id":"R022","trigger":"P161","triggerName":"샤워부스 설치","requires":["P017","P197"],"requiresNames":["우레탄 방수 (욕실)","드레인 설치 (선형)"],"defaultTarget":"P017","relation":"REQUIRES","priority":1,"description":"샤워부스 → 방수+선형드레인 필수","qtyFormulas":{"P017":{"type":"fixed","value":4},"P197":{"type":"fixed","value":1.2}}}'::jsonb,'ontology.json'),
('HQ','R023','P074','목재 데크 설치','RECOMMENDS',array['P110','P021']::text[],array['목재 오일 스테인','방수 줄눈 처리']::text[],'P110',null,null,'{"P110":{"type":"multiply","factor":1},"P021":{"type":"perimeter"}}'::jsonb,2,'목재 데크 → 오일스테인+줄눈 권장','{"id":"R023","trigger":"P074","triggerName":"목재 데크 설치","requires":["P110","P021"],"requiresNames":["목재 오일 스테인","방수 줄눈 처리"],"defaultTarget":"P110","relation":"RECOMMENDS","priority":2,"description":"목재 데크 → 오일스테인+줄눈 권장","qtyFormulas":{"P110":{"type":"multiply","factor":1},"P021":{"type":"perimeter"}}}'::jsonb,'ontology.json'),
('HQ','R024','P107','에폭시 바닥 도장','REQUIRES',array['P036','P105']::text[],array['셀프레벨링 (바닥평탄화)','페인트 하도 처리 (프라이머)']::text[],'P036',null,null,'{"P036":{"type":"multiply","factor":1},"P105":{"type":"multiply","factor":1}}'::jsonb,1,'에폭시 도장 전 평탄화+프라이머 필수','{"id":"R024","trigger":"P107","triggerName":"에폭시 바닥 도장","requires":["P036","P105"],"requiresNames":["셀프레벨링 (바닥평탄화)","페인트 하도 처리 (프라이머)"],"defaultTarget":"P036","relation":"REQUIRES","priority":1,"description":"에폭시 도장 전 평탄화+프라이머 필수","qtyFormulas":{"P036":{"type":"multiply","factor":1},"P105":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R025','P138','외단열 시스템 (EIFS)','REQUIRES',array['P039','P103']::text[],array['외벽 스타코 미장','탄성도료 외벽']::text[],'P039',null,null,'{"P039":{"type":"multiply","factor":1},"P103":{"type":"multiply","factor":1}}'::jsonb,1,'외단열 → 스타코미장+탄성도료 마감','{"id":"R025","trigger":"P138","triggerName":"외단열 시스템 (EIFS)","requires":["P039","P103"],"requiresNames":["외벽 스타코 미장","탄성도료 외벽"],"defaultTarget":"P039","relation":"REQUIRES","priority":1,"description":"외단열 → 스타코미장+탄성도료 마감","qtyFormulas":{"P039":{"type":"multiply","factor":1},"P103":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R026','P065','문틀 설치 (ABS)','REQUIRES',array['P066','P191']::text[],array['문짝 설치 (ABS)','문선 설치 (ABS)']::text[],'P066',null,null,'{"P066":{"type":"multiply","factor":1},"P191":{"type":"multiply","factor":6}}'::jsonb,1,'문틀 → 문짝+문선 세트','{"id":"R026","trigger":"P065","triggerName":"문틀 설치 (ABS)","requires":["P066","P191"],"requiresNames":["문짝 설치 (ABS)","문선 설치 (ABS)"],"defaultTarget":"P066","relation":"REQUIRES","priority":1,"description":"문틀 → 문짝+문선 세트","qtyFormulas":{"P066":{"type":"multiply","factor":1},"P191":{"type":"multiply","factor":6}}}'::jsonb,'ontology.json'),
('HQ','R027','P016','우레탄 방수 (평지붕)','RECOMMENDS',array['P025']::text[],array['방수 테스트 (물채움)']::text[],'P025',null,null,'{"P025":{"type":"fixed","value":1}}'::jsonb,2,'평지붕 방수 후 물채움 테스트 권장','{"id":"R027","trigger":"P016","triggerName":"우레탄 방수 (평지붕)","requires":["P025"],"requiresNames":["방수 테스트 (물채움)"],"defaultTarget":"P025","relation":"RECOMMENDS","priority":2,"description":"평지붕 방수 후 물채움 테스트 권장","qtyFormulas":{"P025":{"type":"fixed","value":1}}}'::jsonb,'ontology.json'),
('HQ','R028','P026','190블록 쌓기','REQUIRES',array['P034']::text[],array['벽 시멘트 미장']::text[],'P034',null,null,'{"P034":{"type":"multiply","factor":1}}'::jsonb,1,'블록조적 → 미장 마감 필수','{"id":"R028","trigger":"P026","triggerName":"190블록 쌓기","requires":["P034"],"requiresNames":["벽 시멘트 미장"],"defaultTarget":"P034","relation":"REQUIRES","priority":1,"description":"블록조적 → 미장 마감 필수","qtyFormulas":{"P034":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json'),
('HQ','R029','P123','온돌마루 시공','REQUIRES',array['P064','P063']::text[],array['목재 몰딩 설치','목재 걸레받이 설치']::text[],'P064',null,null,'{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"}}'::jsonb,1,'온돌마루 → 몰딩+걸레받이','{"id":"R029","trigger":"P123","triggerName":"온돌마루 시공","requires":["P064","P063"],"requiresNames":["목재 몰딩 설치","목재 걸레받이 설치"],"defaultTarget":"P064","relation":"REQUIRES","priority":1,"description":"온돌마루 → 몰딩+걸레받이","qtyFormulas":{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"}}}'::jsonb,'ontology.json'),
('HQ','R030','P131','헤링본 강마루','REQUIRES',array['P064','P063','P036']::text[],array['목재 몰딩 설치','목재 걸레받이 설치','셀프레벨링 (바닥평탄화)']::text[],'P036',null,null,'{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"},"P036":{"type":"multiply","factor":1}}'::jsonb,1,'헤링본 → 평탄화+몰딩+걸레받이','{"id":"R030","trigger":"P131","triggerName":"헤링본 강마루","requires":["P064","P063","P036"],"requiresNames":["목재 몰딩 설치","목재 걸레받이 설치","셀프레벨링 (바닥평탄화)"],"defaultTarget":"P036","relation":"REQUIRES","priority":1,"description":"헤링본 → 평탄화+몰딩+걸레받이","qtyFormulas":{"P064":{"type":"perimeter"},"P063":{"type":"perimeter"},"P036":{"type":"multiply","factor":1}}}'::jsonb,'ontology.json')
on conflict (tenant_id,rule_id) do update set trigger_code = excluded.trigger_code, trigger_name = excluded.trigger_name, relation = excluded.relation, targets = excluded.targets, target_names = excluded.target_names, default_target = excluded.default_target, condition = excluded.condition, quantity_calc = excluded.quantity_calc, qty_formulas = excluded.qty_formulas, priority = excluded.priority, description = excluded.description, raw = excluded.raw, origin_dataset = excluded.origin_dataset, updated_at = now();

insert into public.ontology_rules (tenant_id,rule_id,trigger_code,trigger_name,relation,targets,target_names,default_target,condition,quantity_calc,qty_formulas,priority,description,raw,origin_dataset)
values
('HQ','OR-001',null,'LGS 경량틀 (천장/벽)','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'골조 완료 후','{"triggerProcess":"LGS 경량틀 (천장/벽)","relationshipType":"필수","autoLinkProcess":"석고보드 (9.5T or 12.5T)","condition":"항상","quantityCalc":"동일면적","note":"골조 완료 후"}'::jsonb,'ontology-rules.json'),
('HQ','OR-002',null,'바닥 타일 시공','필수','{}','{}',null,'욕실/습식공간','타일면적 × 1.1','{}'::jsonb,null,'방수 선행 필수','{"triggerProcess":"바닥 타일 시공","relationshipType":"필수","autoLinkProcess":"욕실방수 + 보호몰탈","condition":"욕실/습식공간","quantityCalc":"타일면적 × 1.1","note":"방수 선행 필수"}'::jsonb,'ontology-rules.json'),
('HQ','OR-003',null,'바닥 타일 시공','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'양생 24h','{"triggerProcess":"바닥 타일 시공","relationshipType":"필수","autoLinkProcess":"타일 줄눈 시공","condition":"항상","quantityCalc":"동일면적","note":"양생 24h"}'::jsonb,'ontology-rules.json'),
('HQ','OR-004',null,'헤링본 바닥타일','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'평탄도 ±2mm','{"triggerProcess":"헤링본 바닥타일","relationshipType":"필수","autoLinkProcess":"셀프레벨링 (평탄화)","condition":"항상","quantityCalc":"동일면적","note":"평탄도 ±2mm"}'::jsonb,'ontology-rules.json'),
('HQ','OR-005',null,'대형 포세린 (800↑)','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'레이탄스 제거','{"triggerProcess":"대형 포세린 (800↑)","relationshipType":"필수","autoLinkProcess":"셀프레벨링 + 클립","condition":"항상","quantityCalc":"동일면적","note":"레이탄스 제거"}'::jsonb,'ontology-rules.json'),
('HQ','OR-006',null,'강마루/원목/온돌마루','필수','{}','{}',null,'항상','둘레 기반','{}'::jsonb,null,'실리콘 마감','{"triggerProcess":"강마루/원목/온돌마루","relationshipType":"필수","autoLinkProcess":"목재 몰딩 + 걸레받이","condition":"항상","quantityCalc":"둘레 기반","note":"실리콘 마감"}'::jsonb,'ontology-rules.json'),
('HQ','OR-007',null,'원목마루','권장','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'1년 주기','{"triggerProcess":"원목마루","relationshipType":"권장","autoLinkProcess":"목재 오일스테인","condition":"항상","quantityCalc":"동일면적","note":"1년 주기"}'::jsonb,'ontology-rules.json'),
('HQ','OR-008',null,'수성페인트 (벽)','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'2회 샌딩','{"triggerProcess":"수성페인트 (벽)","relationshipType":"필수","autoLinkProcess":"퍼티 + 프라이머","condition":"항상","quantityCalc":"동일면적","note":"2회 샌딩"}'::jsonb,'ontology-rules.json'),
('HQ','OR-009',null,'수성페인트 (천장)','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'흡수율 조절','{"triggerProcess":"수성페인트 (천장)","relationshipType":"필수","autoLinkProcess":"프라이머 도포","condition":"항상","quantityCalc":"동일면적","note":"흡수율 조절"}'::jsonb,'ontology-rules.json'),
('HQ','OR-010',null,'실크/천연벽지 도배','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'이음 보강','{"triggerProcess":"실크/천연벽지 도배","relationshipType":"필수","autoLinkProcess":"초배지 작업","condition":"항상","quantityCalc":"동일면적","note":"이음 보강"}'::jsonb,'ontology-rules.json'),
('HQ','OR-011',null,'창호 설치 (PVC/AL)','필수','{}','{}',null,'항상','둘레 m','{}'::jsonb,null,'기밀성','{"triggerProcess":"창호 설치 (PVC/AL)","relationshipType":"필수","autoLinkProcess":"EVA 폼 충전 + 코킹","condition":"항상","quantityCalc":"둘레 m","note":"기밀성"}'::jsonb,'ontology-rules.json'),
('HQ','OR-012',null,'욕실방수','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'두께 30mm','{"triggerProcess":"욕실방수","relationshipType":"필수","autoLinkProcess":"보호몰탈 타설","condition":"항상","quantityCalc":"동일면적","note":"두께 30mm"}'::jsonb,'ontology-rules.json'),
('HQ','OR-013',null,'샤워부스 설치','필수','{}','{}',null,'항상','바닥면적','{}'::jsonb,null,'기울기 1/100','{"triggerProcess":"샤워부스 설치","relationshipType":"필수","autoLinkProcess":"욕실방수 + 선형드레인","condition":"항상","quantityCalc":"바닥면적","note":"기울기 1/100"}'::jsonb,'ontology-rules.json'),
('HQ','OR-014',null,'보일러 교체','권장','{}','{}',null,'항상','없음','{}'::jsonb,null,'기밀시험','{"triggerProcess":"보일러 교체","relationshipType":"권장","autoLinkProcess":"난방배관 + 가스배관 점검","condition":"항상","quantityCalc":"없음","note":"기밀시험"}'::jsonb,'ontology-rules.json'),
('HQ','OR-015',null,'문틀 설치','필수','{}','{}',null,'항상','EA','{}'::jsonb,null,'세트 시공','{"triggerProcess":"문틀 설치","relationshipType":"필수","autoLinkProcess":"문짝 + 문선","condition":"항상","quantityCalc":"EA","note":"세트 시공"}'::jsonb,'ontology-rules.json'),
('HQ','OR-016',null,'에폭시 바닥','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'산업용','{"triggerProcess":"에폭시 바닥","relationshipType":"필수","autoLinkProcess":"셀프레벨링 + 프라이머","condition":"항상","quantityCalc":"동일면적","note":"산업용"}'::jsonb,'ontology-rules.json'),
('HQ','OR-017',null,'대리석/화강석','권장','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'정기관리','{"triggerProcess":"대리석/화강석","relationshipType":"권장","autoLinkProcess":"석재 연마/왁스 + 코킹","condition":"항상","quantityCalc":"동일면적","note":"정기관리"}'::jsonb,'ontology-rules.json'),
('HQ','OR-018',null,'조적 (블록쌓기)','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'수직수평','{"triggerProcess":"조적 (블록쌓기)","relationshipType":"필수","autoLinkProcess":"시멘트 미장","condition":"항상","quantityCalc":"동일면적","note":"수직수평"}'::jsonb,'ontology-rules.json'),
('HQ','OR-019',null,'간접등박스','선택','{}','{}',null,'항상','박스 둘레','{}'::jsonb,null,'틀 방식 선택','{"triggerProcess":"간접등박스","relationshipType":"선택","autoLinkProcess":"LGS 경량틀 or 목재틀","condition":"항상","quantityCalc":"박스 둘레","note":"틀 방식 선택"}'::jsonb,'ontology-rules.json'),
('HQ','OR-020',null,'욕실 타일 시공','제안','{}','{}',null,'욕실 리모델링','없음','{}'::jsonb,null,'덧방 or 철거','{"triggerProcess":"욕실 타일 시공","relationshipType":"제안","autoLinkProcess":"욕실 철거 여부 확인","condition":"욕실 리모델링","quantityCalc":"없음","note":"덧방 or 철거"}'::jsonb,'ontology-rules.json'),
('HQ','OR-021',null,'외단열 (EIFS)','필수','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'망 매입','{"triggerProcess":"외단열 (EIFS)","relationshipType":"필수","autoLinkProcess":"외벽 스타코 + 탄성도료","condition":"항상","quantityCalc":"동일면적","note":"망 매입"}'::jsonb,'ontology-rules.json'),
('HQ','OR-022',null,'목재 데크','권장','{}','{}',null,'항상','동일면적','{}'::jsonb,null,'1년 주기','{"triggerProcess":"목재 데크","relationshipType":"권장","autoLinkProcess":"오일스테인 + 줄눈처리","condition":"항상","quantityCalc":"동일면적","note":"1년 주기"}'::jsonb,'ontology-rules.json'),
('HQ','OR-023',null,'방수석고보드','권장','{}','{}',null,'욕실','동일면적','{}'::jsonb,null,'욕실 필수','{"triggerProcess":"방수석고보드","relationshipType":"권장","autoLinkProcess":"욕실방수 + 벽타일","condition":"욕실","quantityCalc":"동일면적","note":"욕실 필수"}'::jsonb,'ontology-rules.json')
on conflict (tenant_id,rule_id) do update set trigger_code = excluded.trigger_code, trigger_name = excluded.trigger_name, relation = excluded.relation, targets = excluded.targets, target_names = excluded.target_names, default_target = excluded.default_target, condition = excluded.condition, quantity_calc = excluded.quantity_calc, qty_formulas = excluded.qty_formulas, priority = excluded.priority, description = excluded.description, raw = excluded.raw, origin_dataset = excluded.origin_dataset, updated_at = now();

insert into public.import_batches (dataset_name, file_name, file_sha256, record_count)
values ('ontology_rules:structured', 'ontology.json', 'b39e025eaf55c45987eb06b46566f1aa51d29ad38d1bdea0fb8f1841d511ec47', 30)
on conflict (dataset_name, file_sha256) do update set record_count = excluded.record_count, imported_at = now();
insert into public.import_batches (dataset_name, file_name, file_sha256, record_count)
values ('ontology_rules:nl', 'ontology-rules.json', '0ba5383669b4df60d00516ab5c749013a94c092e465ea58946979f72a1665aa1', 23)
on conflict (dataset_name, file_sha256) do update set record_count = excluded.record_count, imported_at = now();
