-- 자동 생성: generate-seeds.mjs — 직접 수정 금지, 원본 JSON 수정 후 재생성
-- 멱등: on conflict do update

insert into public.process_categories (tenant_id,code,exposure,input_type,module,condition,formula,enabled,origin_dataset)
values
('HQ','MNG_PM','AUTO','set','config',null,'fixed1',true,'process-categories.json'),
('HQ','MNG_DS','AUTO','set','config',null,'fixed1',true,'process-categories.json'),
('HQ','PRE_PR','CONDITIONAL','area','config','demolition!==없음','totF',true,'process-categories.json'),
('HQ','PRE_FL','AUTO','area','config',null,'dryF',true,'process-categories.json'),
('HQ','PRE_TL','AUTO','area','config',null,'wetF',true,'process-categories.json'),
('HQ','PRE_WL','AUTO','area','config',null,'totW*0.45',true,'process-categories.json'),
('HQ','PRE_CL','AUTO','area','config',null,'totF*0.55',true,'process-categories.json'),
('HQ','PRE_WS','AUTO','qty','config',null,'waste',true,'process-categories.json'),
('HQ','PRE_KT','AUTO','set','config',null,'fixed1',true,'process-categories.json'),
('HQ','FIN_PT','AUTO','area','finish',null,'wallCeil',true,'process-categories.json'),
('HQ','FIN_ML','AUTO','qty','space',null,'mlEA',true,'process-categories.json'),
('HQ','FIN_BB','AUTO','qty','space',null,'mlEA',true,'process-categories.json'),
('HQ','FIN_SL','AUTO','len','space',null,'totF*0.26',true,'process-categories.json'),
('HQ','ELE_WR','AUTO','qty','elec',null,'wpts',true,'process-categories.json'),
('HQ','END_CL','SELECT','area','handover',null,null,true,'process-categories.json'),
('HQ','END_FI','SELECT','set','handover',null,null,true,'process-categories.json'),
('HQ','END_BK','SELECT','set','handover',null,null,true,'process-categories.json'),
('HQ','CARP_CF','SELECT','area','carp',null,null,true,'process-categories.json'),
('HQ','CARP_CB','SELECT','area','carp',null,null,true,'process-categories.json'),
('HQ','CARP_AW','SELECT','area','carp',null,null,true,'process-categories.json'),
('HQ','CARP_DW','SELECT','qty','carp',null,null,true,'process-categories.json'),
('HQ','CARP_DW2','SELECT','qty','carp',null,null,true,'process-categories.json'),
('HQ','FIN_MR','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_MR2','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_MR3','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_SP','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_SP2','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_LV','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_LV2','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_OW','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_OW2','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_JP','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_CR','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_PA','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_PA2','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_PA3','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_PA4','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_PA5','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_PA6','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_WP','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_WP2','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_WP3','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_WP4','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_WC','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_FM','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_AW','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_AW2','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_MC','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_DK','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','FIN_TX','SELECT','area','finish',null,null,true,'process-categories.json')
on conflict (tenant_id,code) do update set exposure = excluded.exposure, input_type = excluded.input_type, module = excluded.module, condition = excluded.condition, formula = excluded.formula, enabled = excluded.enabled, origin_dataset = excluded.origin_dataset, updated_at = now();

insert into public.process_categories (tenant_id,code,exposure,input_type,module,condition,formula,enabled,origin_dataset)
values
('HQ','FIN_MT','SELECT','area','finish',null,null,true,'process-categories.json'),
('HQ','WIN_SY','SELECT','area','window',null,null,true,'process-categories.json'),
('HQ','WIN_SY2','SELECT','area','window',null,null,true,'process-categories.json'),
('HQ','WIN_SY3','SELECT','area','window',null,null,true,'process-categories.json'),
('HQ','WIN_SYL','SELECT','area','window',null,null,true,'process-categories.json'),
('HQ','WIN_AL','SELECT','area','window',null,null,true,'process-categories.json'),
('HQ','WIN_AL2','SELECT','area','window',null,null,true,'process-categories.json'),
('HQ','WIN_FD','SELECT','area','window',null,null,true,'process-categories.json'),
('HQ','WIN_MD','SELECT','qty','window',null,null,true,'process-categories.json'),
('HQ','WIN_MD2','SELECT','qty','window',null,null,true,'process-categories.json'),
('HQ','WIN_EN','SELECT','qty','door',null,null,true,'process-categories.json'),
('HQ','WIN_SC','SELECT','qty','window',null,null,true,'process-categories.json'),
('HQ','WIN_SC2','SELECT','qty','window',null,null,true,'process-categories.json'),
('HQ','WIN_GL','SELECT','area','window',null,null,true,'process-categories.json'),
('HQ','CARP_DW','SELECT','qty','door',null,null,true,'process-categories.json'),
('HQ','CAB_KT_L','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_KT_U','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_KT_D','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_KT_C','SELECT','qty','furn',null,null,true,'process-categories.json'),
('HQ','CAB_CT_IM','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_CT_QZ','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_CT_CE','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_CT_MR','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_CT_SS','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_BL','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_BL2','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_BL3','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_SH','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_TL','SELECT','qty','furn',null,null,true,'process-categories.json'),
('HQ','CAB_IS','SELECT','qty','furn',null,null,true,'process-categories.json'),
('HQ','CAB_TV','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_BK','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_WD','SELECT','len','furn',null,null,true,'process-categories.json'),
('HQ','CAB_VN','SELECT','qty','furn',null,null,true,'process-categories.json'),
('HQ','CAB_VN2','SELECT','qty','furn',null,null,true,'process-categories.json'),
('HQ','KIT_HV','SELECT','qty','plumb',null,null,true,'process-categories.json'),
('HQ','KIT_HV2','SELECT','qty','plumb',null,null,true,'process-categories.json'),
('HQ','KIT_CP','SELECT','qty','plumb',null,null,true,'process-categories.json'),
('HQ','KIT_IH','SELECT','qty','plumb',null,null,true,'process-categories.json'),
('HQ','KIT_OV','SELECT','qty','plumb',null,null,true,'process-categories.json'),
('HQ','KIT_DW','SELECT','qty','plumb',null,null,true,'process-categories.json'),
('HQ','ELE_OT','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_OT2','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_OT3','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_SW','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_SW2','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_LT','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_LT2','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_LT3','QTY','len','elec',null,null,true,'process-categories.json'),
('HQ','ELE_IL','QTY','len','elec',null,null,true,'process-categories.json')
on conflict (tenant_id,code) do update set exposure = excluded.exposure, input_type = excluded.input_type, module = excluded.module, condition = excluded.condition, formula = excluded.formula, enabled = excluded.enabled, origin_dataset = excluded.origin_dataset, updated_at = now();

insert into public.process_categories (tenant_id,code,exposure,input_type,module,condition,formula,enabled,origin_dataset)
values
('HQ','ELE_DB','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_DB2','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_AC','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_VN','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_VN2','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_IP','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_TV','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_HL','QTY','area','elec',null,null,true,'process-categories.json'),
('HQ','ELE_FD','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','ELE_EV','QTY','qty','elec',null,null,true,'process-categories.json'),
('HQ','PLM_WBS','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_WBD','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_WBF','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_TLS','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_TLD','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_TLI','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_TLB','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_SHS','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_SHD','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_SHF','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_SHR','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_BTS','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_BTD','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_BTI','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_SKS','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_SKF','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_WMS','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_DWS','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_BL','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_HW','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_TP','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_TR','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_TD','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_OD','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','PLM_GS','QTY','qty','plumb',null,null,true,'process-categories.json'),
('HQ','CAB_BL_HG','QTY','len','furn',null,null,true,'process-categories.json'),
('HQ','PRE_BT','CONDITIONAL','qty','config','wetCnt>0','wetCnt',true,'process-categories.json'),
('HQ','PRE_LF','CONDITIONAL','qty','config','myFloor>4','fixed1',true,'process-categories.json'),
('HQ','PRE_EV','CONDITIONAL','qty','config','myFloor>=4','floor-3',true,'process-categories.json'),
('HQ','WET_WP','CONDITIONAL','area','tile','wetF>0','wetF*1.2',true,'process-categories.json'),
('HQ','WET_GR','CONDITIONAL','area','tile','tiles>0','tileArea',true,'process-categories.json'),
('HQ','WET_KT','CONDITIONAL','area','plumb','kitSinks>0 && !tileHasApron','sinkApron',true,'process-categories.json'),
('HQ','BTH_CL','CONDITIONAL','area','space','wetCnt>0','wetF',true,'process-categories.json'),
('HQ','BTH_MR','CONDITIONAL','qty','space','wetCnt>0','wetCnt',true,'process-categories.json'),
('HQ','BTH_AC','CONDITIONAL','qty','space','wetCnt>0','wetCnt',true,'process-categories.json'),
('HQ','BTH_VN','CONDITIONAL','qty','space','wetCnt>0','wetCnt',true,'process-categories.json'),
('HQ','AC_IN','CONDITIONAL','qty','elec','ac>0','ac',true,'process-categories.json')
on conflict (tenant_id,code) do update set exposure = excluded.exposure, input_type = excluded.input_type, module = excluded.module, condition = excluded.condition, formula = excluded.formula, enabled = excluded.enabled, origin_dataset = excluded.origin_dataset, updated_at = now();

insert into public.import_batches (dataset_name, file_name, file_sha256, record_count)
values ('process_categories', 'process-categories.json', '64a4def8a153753dfb8a25fae722954ce9ca13a84eeacdc4451ff802ede0c82c', 147)
on conflict (dataset_name, file_sha256) do update set record_count = excluded.record_count, imported_at = now();
